### PR TITLE
Give code review

### PR DESCRIPTION
**Pull request by Lawmsangi**
In this projected, I implemented the following:
-  Added Home page
- Added About page
-  Added Login Page
- To-do-list-page where users can add, edit and delete tasks.
- Linters error-free

### CODE REVIEW

**Review by Bupilipili — APPROVED** [review]
**### Status: Approved 🟢**
well-1
Your project is complete! There is nothing else to say other than... it's time to merge it 👍 shipit:
Congratulations! 🎉

Highlights
✔️ The repo is professional according to the [basic rules]
✔️ Descriptive README file.
✔️ Meaningful Commit history.
✔️ Professional PR
✔️ Check linters
✔️ Descriptive Branch name.
✔️ App works as expected.
✔️ App runs successfully.
✔️ Hooks (useEffect, useState)
✔️ Props and state usage.
✔️ Good job using Vite.
✔️ Good quality code (DRY, KISS, and YAGNI).
✔️ Good Job implemented the required changes
✔️ Routing
✔️ Add navbar
✔️ GitFlow

Cheers, and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please tag me in your question so I can receive the notification. You can tag me by typing @Bupilipili
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by Bupilipili — CHANGES_REQUESTED** [review]
kindly set up your README.md file

**Comment by Lawmsangi** [comment]
> kindly set up your README.md file

Sure,I have done it. Thank you!

**Review by Bupilipili — APPROVED** [review]
Hi @Lawmsangi  ,

Your project is complete! There is nothing else to say other than... it's time to merge it 👍 Congratulations! 🎉

Highlights
Descriptive Readme file✔️
Linters check passed✔️
Meaningful Commit history.✔️
Professional PR✔️
Check linters✔️
App runs successfully✔️.
Hooks (useEffect, useState)✔️
Props and state usage.✔️
Good quality code (DRY, KISS, and YAGNI).✔️
Used Gitflow ✔️

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @Bupilipili  in your question so I can receive the notification.

**Pull request merged**
